"""Add status to messages

Revision ID: 0d2d2f78646b
Revises: 70ac740c186c
Create Date: 2026-08-07 21:09:51.327157

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0d2d2f78646b"
down_revision: str | Sequence[str] | None = "70ac740c186c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum = postgresql.ENUM(
        "PARTIAL", "PENDING", "COMPLETED", "FAILED", name="message_status_enum"
    )
    status_enum.create(op.get_bind(), checkfirst=True)

    # 2. Add the column WITH a server_default for existing rows
    op.add_column(
        "messages",
        sa.Column(
            "status",
            sa.Enum(
                "PARTIAL", "PENDING", "COMPLETED", "FAILED", name="message_status_enum"
            ),
            nullable=False,
            server_default="COMPLETED",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Drop the column first
    op.drop_column("messages", "status")

    # 2. Explicitly drop the ENUM type from PostgreSQL
    status_enum = postgresql.ENUM(
        "PARTIAL", "PENDING", "COMPLETED", "FAILED", name="message_status_enum"
    )
    status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
