"""Add message table

Revision ID: 8e40c2a9ac8d
Revises: e4c582d8673e
Create Date: 2026-08-07 13:54:00.467331

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "8e40c2a9ac8d"
down_revision: str | Sequence[str] | None = "e4c582d8673e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
