"""add_document_status

Revision ID: 977522bb812c
Revises: 9a7c2e4f1b6d
Create Date: 2026-08-20 21:39:16.371465

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "977522bb812c"
down_revision: str | Sequence[str] | None = "9a7c2e4f1b6d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE document_status_enum AS ENUM "
        "('pending','processing','completed','failed')"
    )

    op.add_column(
        "documents",
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "completed",
                "failed",
                name="document_status_enum",
            ),
            nullable=False,
            server_default="pending",
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("documents", "status")
    op.execute("DROP TYPE document_status_enum")
